name: CI

on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"

env:
  RUSTFLAGS: -D warnings

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable-x86_64-pc-windows-msvc
          - stable-x86_64-apple-darwin
          - stable-x86_64-unknown-linux-gnu
          - beta-x86_64-unknown-linux-gnu
          - nightly-x86_64-unknown-linux-gnu
        include:
          - toolchain: stable-x86_64-pc-windows-msvc
            os: windows-latest
          - toolchain: stable-x86_64-apple-darwin
            os: macos-latest
          - toolchain: stable-x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - toolchain: beta-x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - toolchain: nightly-x86_64-unknown-linux-gnu
            os: ubuntu-latest
    name: Check on ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: rust-toolchain ( ${{ matrix.toolchain }} )
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: "`cargo check`"
        run: cargo check --all-targets --all-features
      - name: "`cargo test`"
        run: cargo test --no-fail-fast --verbose --locked

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: "`cargo clippy`"
        run: cargo clippy --all-targets --all-features

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
    name: GitHub Release (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    needs: [check, clippy]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: "`cargo build --release`"
        run: cargo build --release --target ${{ matrix.target }}
      - name: Create an asset
        id: asset
        run: |
          if ${{ contains(matrix.target, 'pc-windows') }}; then
            EXE=.exe
          fi
          EXECUTABLE="./target/${{ matrix.target }}/release/${GITHUB_REPOSITORY#*/}$EXE"
          ASSET_STEM="${GITHUB_REPOSITORY#*/}-${GITHUB_REF#refs/tags/}-${{ matrix.target }}"
          git archive -o "./$ASSET_STEM.tar" --prefix "$ASSET_STEM/" HEAD
          tar -xf "./$ASSET_STEM.tar"
          mv "$EXECUTABLE" "./$ASSET_STEM/"
          if ${{ contains(matrix.target, 'pc-windows') }}; then
            ASSET="./$ASSET_STEM.zip"
            7z a "$ASSET" "./$ASSET_STEM"
            zipinfo "$ASSET"
          else
            ASSET="./$ASSET_STEM.tar.gz"
            tar -czvf "$ASSET" "./$ASSET_STEM"
          fi
          echo "asset=$ASSET" >> $GITHUB_OUTPUT
        shell: bash
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.asset.outputs.asset }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: [check, clippy]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: publish
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
